---
- hosts: app
  tasks:
    - import_role:
        name: node_app.nginx
      vars:
        local_app_path: /var/lib/jenkins/workspace/SQLSite/dist/
        appname: sqdsite
        server_name: "app.shibaoxu.cn"
    